[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.obj.schemas"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.schemas"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
